name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make -j$(nproc) test
      - uses: pixelcmtd/markdown-doctest-action@v0.1
        with:
            flags: -I. -Wall -Wextra -std=c++17 -pedantic
